Repository CycloneDX/cyclonedx-python-lib, pull requests merged in 2021-11, with the labels that each got.

#43 fixed typehints/docs in `_BaseCondaParser`
  cyclonedx/parser/conda.py
Labels: bug

#42 slacked pipenv parser
  cyclonedx/parser/pipenv.py
  tests/fixtures/pipfile-lock-simple.txt
  tests/test_parser_pipenv.py
Labels: enhancement

#41 fixed some abstract definitions
  cyclonedx/output/schema.py
  cyclonedx/parser/conda.py
Labels: enhancement

#59 typing & PEP 561
  .github/workflows/poetry.yml
  .gitignore
  .mypy.ini
  cyclonedx/exception/__init__.py
  cyclonedx/exception/parser.py
  cyclonedx/model/__init__.py
  cyclonedx/model/bom.py
  cyclonedx/model/component.py
  cyclonedx/model/vulnerability.py
  cyclonedx/output/__init__.py
  cyclonedx/output/json.py
  cyclonedx/output/xml.py
  cyclonedx/parser/__init__.py
  cyclonedx/parser/conda.py
  cyclonedx/parser/environment.py
  cyclonedx/parser/pipenv.py
  cyclonedx/parser/poetry.py
  cyclonedx/parser/requirements.py
  cyclonedx/py.typed
  cyclonedx/utils/conda.py
  poetry.lock
  pyproject.toml
  tests/.DS_Store
  tests/base.py
  tests/test_bom.py
  tests/test_component.py
  tests/test_e2e_environment.py
  tests/test_model.py
  tests/test_model_component.py
  tests/test_model_vulnerability.py
  tests/test_output_generic.py
  tests/test_output_json.py
  tests/test_output_xml.py
  tests/test_parser_conda.py
  tests/test_parser_environment.py
  tests/test_parser_pipenv.py
  tests/test_parser_poetry.py
  tests/test_parser_requirements.py
  tests/test_utils_conda.py
  tox.ini
Labels: enhancement

#64 FEAT: Support Python 3.10
  .github/workflows/docs.yml
  .github/workflows/poetry.yml
  pyproject.toml
  tox.ini
Labels: enhancement

#61 model/vulnerability: fix optional type
  cyclonedx/model/vulnerability.py
Labels: bug

#66 FIX: update Conda package parsing to handle `build` containing underscore
  cyclonedx/utils/conda.py
  tests/test_utils_conda.py
Labels: bug, enhancement
