Repository CycloneDX/cyclonedx-python-lib, pull requests merged in 2021-12, with the labels that each got.

#79 add tox env for minimal required dependencies
  .github/workflows/poetry.yml
  .mypy.ini
  cyclonedx/model/bom.py
  cyclonedx/output/json.py
  cyclonedx/parser/environment.py
  cyclonedx/utils/conda.py
  pyproject.toml
  requirements.lowest.txt
  tests/test_parser_environment.py
  tox.ini
Labels: dependencies, CI, CT, QA

#95 fix: tightened dependency `packageurl-python`
  poetry.lock
  pyproject.toml
  requirements.lowest.txt
Labels: dependencies

#98 fix: removed requirements-parser as dependency (temp) as not available for Python 3 as Wheel
  poetry.lock
  pyproject.toml
  requirements.lowest.txt
Labels: bug

#93 chore: bump `flake8` to v4 and add `autopep8`
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
Labels: QA

#107 fix: isolated dependencies for building documentation
  .github/workflows/docs.yml
  doc/requirements.txt
Labels: documentation, CI
