Repository CycloneDX/cyclonedx-python-lib, pull requests merged in 2022-01, with the labels that each got.

#109 feat: re-worked for vulnerabilities becoming part of core schema
  cyclonedx/exception/model.py
  cyclonedx/model/__init__.py
  cyclonedx/model/bom.py
  cyclonedx/model/component.py
  cyclonedx/model/impact_analysis.py
  cyclonedx/model/release_note.py
  cyclonedx/model/vulnerability.py
  cyclonedx/output/__init__.py
  cyclonedx/output/json.py
  cyclonedx/output/schema.py
  cyclonedx/output/serializer/__init__.py
  cyclonedx/output/serializer/json.py
  cyclonedx/output/xml.py
  cyclonedx/parser/environment.py
  tests/base.py
  tests/fixtures/bom_v1.2_setuptools.json
  tests/fixtures/bom_v1.3_setuptools.json
  tests/fixtures/bom_v1.3_setuptools_with_vulnerabilities.xml
  tests/fixtures/bom_v1.3_toml_with_component_external_references.json
  tests/fixtures/bom_v1.3_toml_with_component_hashes.json
  tests/fixtures/bom_v1.3_toml_with_component_license.json
  tests/fixtures/bom_v1.3_toml_with_component_license.xml
  tests/fixtures/bom_v1.4_setuptools.json
  tests/fixtures/bom_v1.4_setuptools_with_vulnerabilities.xml
  tests/test_bom.py
  tests/test_component.py
  tests/test_model.py
  tests/test_model_component.py
  tests/test_model_release_note.py
  tests/test_model_vulnerability.py
  tests/test_output_generic.py
  tests/test_output_json.py
  tests/test_output_xml.py
  tests/test_parser_conda.py
  tests/test_parser_environment.py
  tests/test_parser_pipenv.py
  tests/test_parser_poetry.py
Labels: schema 1.4

#121 feat: add support for `$schema` in JSON output
  cyclonedx/output/json.py
  tests/fixtures/bom_v1.2_setuptools.json
  tests/fixtures/bom_v1.3_setuptools.json
  tests/fixtures/bom_v1.3_toml_with_component_external_references.json
  tests/fixtures/bom_v1.3_toml_with_component_hashes.json
  tests/fixtures/bom_v1.3_toml_with_component_license.json
  tests/fixtures/bom_v1.4_setuptools.json
  tests/fixtures/bom_v1.4_setuptools_no_version.json
  tests/fixtures/bom_v1.4_setuptools_with_release_notes.json
  tests/fixtures/bom_v1.4_setuptools_with_vulnerabilities.json
Labels: enhancement

#112 chore: disable poetry-cache in gh-workflow
  .github/workflows/poetry.yml
Labels: CI

#132 feat: Relocate Parsers to `cyclonedx-python`
  cyclonedx/exception/model.py
  cyclonedx/exception/parser.py
  cyclonedx/model/__init__.py
  cyclonedx/parser/conda.py
  cyclonedx/parser/environment.py
  cyclonedx/parser/pipenv.py
  cyclonedx/parser/poetry.py
  cyclonedx/parser/requirements.py
  cyclonedx/utils/__init__.py
  cyclonedx/utils/conda.py
  tests/fixtures/conda-list-explicit-md5.txt
  tests/fixtures/conda-list-explicit.txt
  tests/fixtures/conda-list-output.json
  tests/fixtures/pipfile-lock-no-index-example.txt
  tests/fixtures/pipfile-lock-simple.txt
  tests/fixtures/poetry-lock-simple.txt
  tests/fixtures/requirements-example-1.txt
  tests/fixtures/requirements-multilines-with-comments.txt
  tests/fixtures/requirements-simple.txt
  tests/fixtures/requirements-with-comments.txt
  tests/fixtures/requirements-with-hashes.txt
  tests/fixtures/requirements-without-pinned-versions.txt
  tests/test_bom.py
  tests/test_e2e_environment.py
  tests/test_model.py
  tests/test_parser_conda.py
  tests/test_parser_environment.py
  tests/test_parser_pipenv.py
  tests/test_parser_poetry.py
  tests/test_parser_requirements.py
  tests/test_utils_conda.py
Labels: enhancement

#111 DOCS: describe anaconda release process
  README.md
  docs/install.rst
  docs/processes/release/conda-forge.md
Labels: documentation

#118 Add support for metadata component
  cyclonedx/model/bom.py
  cyclonedx/output/json.py
  cyclonedx/output/xml.py
  tests/fixtures/bom_v1.3_with_metadata_component.json
  tests/fixtures/bom_v1.3_with_metadata_component.xml
  tests/test_bom.py
  tests/test_e2e_environment.py
  tests/test_output_json.py
  tests/test_output_xml.py
Labels: enhancement

#136 chore: bump dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#138 feat: add CPE to component
  cyclonedx/model/component.py
  cyclonedx/output/xml.py
  tests/fixtures/bom_v1.0_setuptools_with_cpe.xml
  tests/fixtures/bom_v1.1_setuptools_with_cpe.xml
  tests/fixtures/bom_v1.2_setuptools_with_cpe.json
  tests/fixtures/bom_v1.2_setuptools_with_cpe.xml
  tests/fixtures/bom_v1.3_setuptools_with_cpe.json
  tests/fixtures/bom_v1.3_setuptools_with_cpe.xml
  tests/fixtures/bom_v1.4_setuptools_with_cpe.json
  tests/fixtures/bom_v1.4_setuptools_with_cpe.xml
  tests/test_output_json.py
  tests/test_output_xml.py
Labels: enhancement

#142 feat: `bom-ref` for Compomnent and Vulnerability default to a UUID
  cyclonedx/model/component.py
  cyclonedx/model/vulnerability.py
  docs/modelling.rst
  tests/fixtures/bom_v1.3_with_metadata_component.json
  tests/fixtures/bom_v1.3_with_metadata_component.xml
  tests/test_model_component.py
  tests/test_model_vulnerability.py
  tests/test_output_json.py
  tests/test_output_xml.py
Labels: enhancement

#145 Next Feature Release
  cyclonedx/model/__init__.py
  cyclonedx/model/bom.py
  cyclonedx/model/issue.py
  cyclonedx/model/service.py
  cyclonedx/output/json.py
  cyclonedx/output/schema.py
  cyclonedx/output/serializer/json.py
  cyclonedx/output/xml.py
  tests/fixtures/bom_v1.2_services_complex.json
  tests/fixtures/bom_v1.2_services_simple.json
  tests/fixtures/bom_v1.3_services_complex.json
  tests/fixtures/bom_v1.3_services_simple.json
  tests/fixtures/bom_v1.4_services_complex.json
  tests/fixtures/bom_v1.4_services_simple.json
  tests/fixtures/bom_v1.4_setuptools_with_vulnerabilities.json
  tests/test_model.py
  tests/test_model_component.py
  tests/test_model_release_note.py
  tests/test_model_service.py
  tests/test_model_vulnerability.py
  tests/test_output_json.py
Labels: enhancement, schema 1.2, schema 1.3, schema 1.4
