Repository CycloneDX/cyclonedx-python-lib, pull requests merged in 2023-01, with the labels that each got.

#339 chore: do not ship exra LICENSE file
  pyproject.toml
Labels: chore

#291 chore: package manifest fix link to homepage and documentation
  pyproject.toml
Labels: documentation

#325 BREAKING CHANGE: remove support for Python3.6
  .github/workflows/poetry.yml
  docs/support.rst
  pyproject.toml
  tox.ini
Labels: breaking change
