Repository CycloneDX/cyclonedx-python-lib, pull requests merged in 2023-03, with the labels that each got.

#349 feat: Support for Python 3.11
  .github/workflows/deploy.yml
  .github/workflows/poetry.yml
  poetry.lock
  pyproject.toml
  requirements.lowest.txt
  tests/test_output_xml.py
  tox.ini
Labels: enhancement

#350 tests: compoennt versions optional
  .isort.cfg
  CONTRIBUTING.md
  tests/test_model_component.py
  tests/test_output_json.py
  tests/test_output_xml.py
  tox.ini
Labels: QA

#359 chore: prevent dev-lowest-lockfile from dependency bumps
  deps.lowest.r
  pyproject.toml
  tox.ini
Labels: chore

#360 chore: clean unused def dependencies
  deps.lowest.r
  pyproject.toml
Labels: dependencies, chore

#361 ci: add concurrency rules
  .github/workflows/deploy.yml
  .github/workflows/manual-release-candidate.yml
  .github/workflows/poetry.yml
Labels: CI

#358 chore: CI/QA/Build meintenance
  .github/workflows/deploy.yml
  .github/workflows/manual-release-candidate.yml
  .github/workflows/poetry.yml
  cyclonedx/model/bom.py
  poetry.lock
Labels: CI, chore
