Repository CycloneDX/cyclonedx-python-lib, pull requests merged in 2024-04, with the labels that each got.

#582 add `acknowledgement` to `LicenseExpression`
  cyclonedx/model/license.py
  cyclonedx/serialization/__init__.py
  tests/_data/models.py
  tests/_data/snapshots/get_bom_with_licenses-1.6.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.6.xml.bin
Labels: enhancement, schema 1.6

#584 docs: missing schema support table & update schema support to reflect version 7.0.0
  docs/schema-support.rst
Labels: documentation

#588 tests: meaningful names to validation tests
  tests/__init__.py
  tests/test_validation_json.py
  tests/test_validation_xml.py
Labels: QA

#591 feat: disjunctive license acknowledgement
  cyclonedx/model/license.py
  tests/_data/models.py
  tests/_data/snapshots/get_bom_with_licenses-1.1.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.2.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.2.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.3.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.3.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.4.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.4.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.5.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.5.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.6.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.6.xml.bin
Labels: enhancement, schema 1.6

#593 feat: license factory set `acknowledgement`
  cyclonedx/factory/license.py
  cyclonedx/model/license.py
  tests/test_factory_license.py
Labels: enhancement

#587 fix: include all fields of `Component` in `__lt__` function for #586
  cyclonedx/model/component.py
Labels: bug

#599 fix: properly sort components based on all properties
  .github/workflows/python.yml
  cyclonedx/_internal/compare.py
  cyclonedx/model/component.py
  tests/_data/models.py
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.0.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.1.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.2.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.2.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.3.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.3.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.4.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.4.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.5.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.5.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.6.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.6.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.1.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.2.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.2.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.3.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.3.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.4.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.4.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.5.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.5.xml.bin
  tests/_data/snapshots/get_bom_with_licenses-1.6.json.bin
  tests/_data/snapshots/get_bom_with_licenses-1.6.xml.bin
Labels: bug
