Repository CycloneDX/cyclonedx-python-lib, pull requests merged in 2024-10, with the labels that each got.

#695 chore: trusted publishing
  .github/workflows/release.yml
Labels: chore

#694 fix: behavior of and typing for crypto setters with optional values
  cyclonedx/model/crypto.py
  tests/_data/own/json/1.6/issue690.json
  tests/test_deserialize_json.py
Labels: bug

#699 chore: ignore coverage of abstract methods
  cyclonedx/model/dependency.py
  cyclonedx/output/__init__.py
  cyclonedx/output/json.py
  cyclonedx/schema/schema.py
  cyclonedx/validation/__init__.py
Labels: QA, chore

#703 docs(chaneglog): omit chore/ci/refactor/style/test/build
  CHANGELOG.md
  pyproject.toml
Labels: documentation

#709 docs: fix code examples regarding outputting
  docs/outputting.rst
Labels: documentation

#698 feat: add support for Lifecycles in BOM metadata
  cyclonedx/model/bom.py
  cyclonedx/model/lifecycle.py
  tests/_data/models.py
  tests/_data/snapshots/enum_LifecyclePhase-1.0.xml.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.1.xml.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.2.json.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.2.xml.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.3.json.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.3.xml.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.4.json.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.4.xml.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.5.json.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.5.xml.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.6.json.bin
  tests/_data/snapshots/enum_LifecyclePhase-1.6.xml.bin
  tests/_data/snapshots/get_bom_just_complete_metadata-1.5.json.bin
  tests/_data/snapshots/get_bom_just_complete_metadata-1.5.xml.bin
  tests/_data/snapshots/get_bom_just_complete_metadata-1.6.json.bin
  tests/_data/snapshots/get_bom_just_complete_metadata-1.6.xml.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.0.xml.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.1.xml.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.2.json.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.2.xml.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.3.json.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.3.xml.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.4.json.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.4.xml.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.5.json.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.5.xml.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.6.json.bin
  tests/_data/snapshots/get_bom_with_lifecycles-1.6.xml.bin
  tests/test_enums.py
  tests/test_model_bom.py
  tests/test_model_lifecycle.py
Labels: enhancement, schema 1.5

#724 fix: encode quotation mark in URL
  cyclonedx/model/__init__.py
  tests/_data/models.py
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.1.xml.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.2.json.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.2.xml.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.3.json.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.3.xml.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.4.json.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.4.xml.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.5.json.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.5.xml.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.6.json.bin
  tests/_data/snapshots/get_bom_for_issue_497_urls-1.6.xml.bin
Labels: bug

#725 docs: revisit examples readme
  examples/README.md
Labels: documentation

#701 feat: add basic support for Definitions
  cyclonedx/_internal/bom_ref.py
  cyclonedx/model/bom.py
  cyclonedx/model/definition.py
  tests/_data/models.py
  tests/_data/snapshots/get_bom_with_definitions_standards-1.0.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.1.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.2.json.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.2.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.3.json.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.3.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.4.json.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.4.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.5.json.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.5.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.6.json.bin
  tests/_data/snapshots/get_bom_with_definitions_standards-1.6.xml.bin
  tests/test_model_definition.py
Labels: enhancement, schema 1.6

#728 feat: add factory method `XsUri.make_bom_link()`
  cyclonedx/model/__init__.py
  cyclonedx/model/bom.py
  tests/test_model.py
Labels: enhancement

#720 fix: no warning for missing dependencies if no component exists
  cyclonedx/model/bom.py
  tests/test_model_bom.py
Labels: bug

#733 docs: remove invalid docsting note about auto-assigned `bom-ref` values
  cyclonedx/model/component.py
  cyclonedx/model/contact.py
  cyclonedx/model/definition.py
  cyclonedx/model/service.py
  cyclonedx/model/vulnerability.py
Labels: documentation
