Repository CycloneDX/cyclonedx-python-lib, pull requests merged in 2025-02, with the labels that each got.

#770 chore: tools shebang
  .flake8
  tools/schema-downloader.py
Labels: chore

#713 feat: add extended support for Definitions
  cyclonedx/exception/model.py
  cyclonedx/model/definition.py
  tests/_data/models.py
  tests/_data/snapshots/get_bom_v1_6_with_crypto-1.6.xml.bin
  tests/_data/snapshots/get_bom_with_crypto-1.6.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.0.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.1.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.2.json.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.2.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.3.json.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.3.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.4.json.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.4.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.5.json.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.5.xml.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.6.json.bin
  tests/_data/snapshots/get_bom_with_definitions_and_detailed_standards-1.6.xml.bin
  tests/test_model_definition.py
Labels: enhancement, schema 1.6

#772 feat: allow empty `OrganizationalContact` object
  cyclonedx/model/contact.py
  tests/_data/own/json/1.6/issue771.json
  tests/test_deserialize_json.py
Labels: enhancement

#755 refactor!: streamline comparison/hashing functions
  cyclonedx/_internal/compare.py
  cyclonedx/model/__init__.py
  cyclonedx/model/bom.py
  cyclonedx/model/component.py
  cyclonedx/model/contact.py
  cyclonedx/model/crypto.py
  cyclonedx/model/definition.py
  cyclonedx/model/dependency.py
  cyclonedx/model/issue.py
  cyclonedx/model/license.py
  cyclonedx/model/lifecycle.py
  cyclonedx/model/release_note.py
  cyclonedx/model/service.py
  cyclonedx/model/tool.py
  cyclonedx/model/vulnerability.py
  tests/test_model_component.py
  tests/test_model_vulnerability.py
Labels: enhancement, breaking change

#775 chore(deps)!: `py-serializable==^1.1.1` -> `^2.0.0`
  cyclonedx/model/__init__.py
  cyclonedx/model/bom.py
  cyclonedx/model/bom_ref.py
  cyclonedx/model/component.py
  cyclonedx/model/contact.py
  cyclonedx/model/crypto.py
  cyclonedx/model/definition.py
  cyclonedx/model/dependency.py
  cyclonedx/model/impact_analysis.py
  cyclonedx/model/issue.py
  cyclonedx/model/license.py
  cyclonedx/model/lifecycle.py
  cyclonedx/model/release_note.py
  cyclonedx/model/service.py
  cyclonedx/model/tool.py
  cyclonedx/model/vulnerability.py
  cyclonedx/schema/schema.py
  cyclonedx/serialization/__init__.py
  pyproject.toml
Labels: dependencies, breaking change

#754 feat!: BomRef affect equality/comparisson
  cyclonedx/model/component.py
  cyclonedx/model/contact.py
  cyclonedx/model/definition.py
  cyclonedx/model/service.py
  cyclonedx/model/vulnerability.py
  tests/_data/models.py
  tests/_data/own/json/1.5/issue677.json
  tests/_data/own/json/1.5/issue753.json
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.0.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.1.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.2.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.2.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.3.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.3.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.4.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.4.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.5.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.5.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.6.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.6.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.0.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.1.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.2.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.2.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.3.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.3.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.4.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.4.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.5.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.5.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.6.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.6.xml.bin
  tests/test_model_component.py
  tests/test_model_vulnerability.py
  tests/test_real_world_examples.py
Labels: enhancement, breaking change

#767 feat: add `cyclonedx.model.crypto.ProtocolProperties.crypto_refs`
  cyclonedx/model/crypto.py
  tests/_data/models.py
  tests/_data/snapshots/get_bom_for_issue_692_components-1.0.xml.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.1.xml.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.2.json.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.2.xml.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.3.json.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.3.xml.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.4.json.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.4.xml.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.5.json.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.5.xml.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.6.json.bin
  tests/_data/snapshots/get_bom_for_issue_692_components-1.6.xml.bin
  tests/test_deserialize_json.py
Labels: enhancement, schema 1.6

#782 tests: revisit `spdx.is_expression()`
  tests/test_spdx.py
Labels: QA

#783 docs: extended instructions for "contributing"
  CONTRIBUTING.md
Labels: documentation

#786 feat: avoid raising `NoPropertiesProvidedException` for optional parameters
  cyclonedx/model/__init__.py
  cyclonedx/model/component.py
  cyclonedx/model/issue.py
  cyclonedx/model/vulnerability.py
  tests/test_model.py
  tests/test_model_component.py
  tests/test_model_issue.py
Labels: enhancement

#777 feat!: 9.0.1
  cyclonedx/__init__.py
  cyclonedx/_internal/compare.py
  cyclonedx/factory/license.py
  cyclonedx/model/__init__.py
  cyclonedx/model/bom.py
  cyclonedx/model/bom_ref.py
  cyclonedx/model/component.py
  cyclonedx/model/contact.py
  cyclonedx/model/crypto.py
  cyclonedx/model/definition.py
  cyclonedx/model/dependency.py
  cyclonedx/model/impact_analysis.py
  cyclonedx/model/issue.py
  cyclonedx/model/license.py
  cyclonedx/model/lifecycle.py
  cyclonedx/model/release_note.py
  cyclonedx/model/service.py
  cyclonedx/model/tool.py
  cyclonedx/model/vulnerability.py
  cyclonedx/schema/schema.py
  cyclonedx/serialization/__init__.py
  cyclonedx/spdx.py
  docs/conf.py
  pyproject.toml
  tests/_data/models.py
  tests/_data/own/json/1.5/issue677.json
  tests/_data/own/json/1.5/issue753.json
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.0.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.1.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.2.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.2.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.3.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.3.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.4.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.4.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.5.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.5.xml.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.6.json.bin
  tests/_data/snapshots/get_bom_for_issue540_duplicate_components-1.6.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.0.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.1.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.2.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.2.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.3.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.3.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.4.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.4.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.5.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.5.xml.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.6.json.bin
  tests/_data/snapshots/get_bom_for_issue_598_multiple_components_with_purl_qualifiers-1.6.xml.bin
  tests/test_factory_license.py
  tests/test_model_component.py
  tests/test_model_vulnerability.py
  tests/test_real_world_examples.py
  tests/test_spdx.py
Labels: bug, enhancement, dependencies, breaking change

#794 feat: VulnerabilityAnalysis properties for issued/updated datetime
  cyclonedx/model/vulnerability.py
  tests/_data/models.py
  tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.5.json.bin
  tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.5.xml.bin
  tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.6.json.bin
  tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.6.xml.bin
Labels: enhancement

#795 fix: improved comparison functionality of `model.VulnerabilityAnalysis`
  cyclonedx/model/vulnerability.py
Labels: bug
